name: Build Thanox Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Release APK
        run: gradle :thanox-app:assembleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: thanox-release-apk
          path: thanox-app/build/outputs/apk/release/*.apk